"use strict";
var myName = "Muhammad Junaid";
var message = "I have strated learning TYPESCRIPT";
console.log(`\n${myName}, ${message}`);
var num1 = 15;
var num2 = 22;
var num3 = 38;
var num4 = 47;
var num5 = 59;
var num6 = 61;
var num7 = 73;
var num8 = 85;
var num9 = 96;
var num10 = 150;
console.log("Assignment: Basic mathematical operations of at least 10 numbers");
console.log("Assignment Date: 23 July 2023");
var sum = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10);
console.log("Sum of all the numbers are:");
console.log(sum);
var subtraction = (num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10);
console.log("Subtraction of all the numbers are:");
console.log(subtraction);
var multiplication = (num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10);
console.log("Multiplication of all the numbers are:");
console.log(multiplication);
var division = (num10 / num1);
console.log("Division of two numbers are:");
console.log(division);
