var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'honda'? I predict True.");
console.log(car != 'honda');
console.log("Is car.length > 4? I predict True.");
console.log(car.length > 4);
console.log("Is car.length == 6? I predict True.");
console.log(car.length == 6);
console.log("Is car.toLowerCase() == 'subaru'? I predict True.");
console.log(car.toLowerCase() == 'subaru');
console.log("Is car == 'Subaru'? I predict False.");
console.log(car == 'Subaru');
console.log("Is car.toUpperCase() != 'SUBARU'? I predict False.");
console.log(car.toUpperCase() != 'SUBARU');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
console.log("Is car.length == 5? I predict False.");
console.log(car.length == 5);
console.log("Is car.length > 6? I predict False.");
console.log(car.length > 6);
