FROM apache/kafka:3.7.0

# Expose ports
EXPOSE 9092

# If you need to add any custom configuration, you can copy it here
# COPY custom_kafka_config.properties /kafka/config/kafka.properties

# No custom CMD needed, as the image's default entrypoint is sufficient
