FROM postgres:latest

# Environment variables for PostgreSQL
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=online_mart

# Expose the default PostgreSQL port
EXPOSE 5432

# No additional configuration needed as we use environment variables
